includes:
  - https://github.ibm.com/cloud-docs/gateway-appliance
  - https://github.ibm.com/cloud-docs/FortiGate-10g
  - https://github.ibm.com/cloud-docs/cloud-infrastructure
  - https://github.ibm.com/cloud-docs-solutions/solution-tutorials
  - https://github.ibm.com/cloud-docs/vfsa
translation:
  exclude:
    byFilePath:
      - file-dont-translate.md
      - folder-dont-translate/
